import sbt.Keys.sourceManaged
import sbt._

object Versions {
  val swagger = new {
    val core = "1.5.21"
  }
  val classutil = "1.3.0"

  val createVersionsFileTask: Def.Initialize[Task[Seq[File]]] = Def.task {
    val srcManaged = (sourceManaged in Compile).value

    createVersionsFile(srcManaged, swagger.core)
  }

  private def createVersionsFile(base: File, swaggerCoreVersion: String): Seq[File] = {
    val output = base / "swagger" / "meta" / "Versions.scala"

    val versionsBody =
      s"""/**
         |  * This file was generated by `project/Versions.scala` in sbt-swagger-meta.
         |  * So you must not edit this file.
         |  */
         |
         |package swagger.meta
         |
         |object Versions {
         |  val swaggerCoreVersion: String = "$swaggerCoreVersion"
         |}
         |""".stripMargin

    IO.write(output, versionsBody)
    Seq(output)
  }
}
