import sbt.Keys.sourceManaged
import sbt._

object Versions {
  val swagger = new {
    val core = "1.5.24"
    val scalaModule = "1.0.4"
  }
  val classutil = "1.3.0"

  val jacksonModuleScala = "2.9.6"

  val json4s = "3.6.1"

  lazy val createVersionsFileTask: Def.Initialize[Task[Seq[File]]] = Def.task {
    val output = (sourceManaged in Compile).value / "sbtswaggermeta" / "Versions.scala"

    val versionsBody =
      s"""/**
         |  * This file was generated by `project/Versions.scala` in sbt-swagger-meta.
         |  * So you must not edit this file.
         |  */
         |
         |package sbtswaggermeta
         |
         |object Versions {
         |  val swaggerCoreVersion: String = "${swagger.core}"
         |}
         |""".stripMargin

    IO.write(output, versionsBody)
    Seq(output)
  }
}
